services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest

    container_name: cadvisor

    restart: unless-stopped

    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

    labels:
      - traefik.enable=true

      - traefik.http.routers.cadvisor.rule=Host(`cadvisor.orbyz.lab`)
      - traefik.http.routers.cadvisor.entrypoints=web

      - traefik.http.services.cadvisor.loadbalancer.server.port=8080

    networks:
      - homelab

networks:
  homelab:
    external: true
