services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.lab,192.168.1.5,localhost

    volumes:
      - /home/OrByZ/workspace/infrastructure/homelab/data/homepage:/app/config

    networks:
      - homelab

networks:
  homelab:
    external: true
