services:
  caddy:
    image: caddy:2.10
    container_name: caddy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /home/OrByZ/workspace/infrastructure/homelab/data/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /home/OrByZ/workspace/infrastructure/homelab/data/caddy/data:/data
      - /home/OrByZ/workspace/infrastructure/homelab/data/caddy/config:/config

    networks:
      - homelab

networks:
  homelab:
    external: true
