services:
  traefik:
    image: traefik:v3.6.1
    container_name: traefik

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DOCKER_API_VERSION: "1.55"

    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "80:80"
      - "8081:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./letsencrypt:/letsencrypt

    networks:
      - homelab

networks:
  homelab:
    external: true
